Privacy Policy（隐私政策）

English Version

Thank you for using QuitMe.

We value your privacy. This app does not collect, store, or share any personally identifiable information.

1. Information Collection and Use

This app does not require user registration and does not collect:

Name, email address, or phone number

Identification information

Precise location data

Some features (such as Daily Quotes, Daily Words, and Online Dictionary) require network access to retrieve content. These requests do not include any personally identifiable information.

2. Permissions

To provide core functionality, the app may request the following permissions:

Storage: to save images generated by the user to the local device

Audio: to play in-app sound effects

Vibration: to provide haptic feedback

Internet access: to retrieve online content

These permissions are used only for their stated purposes.

3. Third-Party Services

The app may use third-party APIs (such as online dictionary or content services) to deliver features.
We do not share personal data with third parties, nor do we sell user data.

4. Children’s Privacy

This app is not intended for children under the age of 13.
We do not knowingly collect personal information from children. If you believe that such information has been collected inadvertently, please contact us and we will promptly remove it.

5. Changes to This Privacy Policy

We may update this Privacy Policy from time to time. Any changes will be posted on this page.
Please review this policy periodically.

6. Contact Us

If you have any questions about this Privacy Policy, please contact us at:

📧 Email: gosi2025618@gmail.com


中文版

感谢您使用 戒了么（QuitMe）。

我们非常重视您的隐私。本应用不会收集、存储或分享任何可用于识别您个人身份的信息。

1. 信息收集与使用

本应用 不会要求用户注册账号，也不会主动收集以下信息：

姓名、邮箱、电话号码

身份证件信息

精确位置信息

应用中的部分功能（如每日金句、每日一词、在线词典）需要通过网络请求获取内容，但这些请求 不包含任何可识别个人身份的信息。

2. 权限说明

为了实现应用功能，本应用可能会请求以下权限：

存储权限：用于将用户生成的图片保存到本地设备

声音权限：用于播放应用内提示音效

振动权限：用于提供操作反馈体验

网络访问权限：用于获取在线内容（如每日金句、在线词典）

上述权限仅用于实现相应功能，不会用于其他用途。

3. 第三方服务

本应用可能使用第三方 API（例如在线词典或内容接口）来提供核心功能。
我们不会与任何第三方共享您的个人数据，也不会向第三方出售用户数据。

4. 儿童隐私

本应用不以 13 周岁以下儿童为目标用户。
我们不会有意收集任何儿童的个人信息。如果您认为我们无意中收集了儿童信息，请通过下方联系方式与我们联系，我们将及时处理。

5. 隐私政策的变更

如本隐私政策有任何更新，我们将在本页面进行说明。
建议您定期查看本政策以了解最新信息。

6. 联系我们

如果您对本隐私政策有任何疑问，请通过以下方式联系我们：

📧 邮箱：gosi2025618@gmail.com
